//! Protocol message definitions
//!
//! This module provides access to all Nexa-net protocol types:
//! - Proto-generated types from the proto/ directory definitions
//! - Higher-level Rust-native message types with additional logic
//!
//! The proto-generated types provide Protobuf serialization,
//! while the Rust-native types add business logic, validation,
//! and convenient constructors.
//!
//! # Module layout for proto-generated types
//!
//! Common types (nexa.protocol package) are included directly in this module,
//! so that sub-package types in `proto` can reference them via `super::`.
//! This matches the `super::` references generated by prost-build for
//! cross-package type references (e.g., identity.proto referencing
//! CompressionType from nexa_common.proto).

// Common protocol types (nexa.protocol package) — included at this level
// so sub-package types in `proto` module can reference them via `super::`
include!(concat!(env!("OUT_DIR"), "/nexa.protocol.rs"));

// Sub-package protocol types (identity, discovery, transport, economy)
// These use `super::` to reference common types defined above
pub mod proto;

// Higher-level Rust-native protocol message types
// Note: message.rs provides Rust-native convenience wrappers that
// complement the proto-generated types. Proto-generated NexaMessage,
// MessageHeader, and MessageSignature are the canonical Protobuf types;
// message.rs provides the same names with serde support and constructors.
pub mod discovery;
pub mod economy;
pub mod identity;
pub mod message;
pub mod transport;
